Repository swapnanildutta/Hackerrank-Codes, pull requests merged in 2020-10, with the labels that each got.

#81 Mathematics Section 4 solutions added
  Mathematics/Army Game.java
  Mathematics/Find the Point.java
  Mathematics/HandShake.java
  Mathematics/README.md
  Solution.java
Labels: hacktoberfest-accepted

#264 Added README
  30 Days of Code (Python)/README.md
Labels: hacktoberfest-accepted

#287 hackerrank problem solving commonchild and larry'sArray
  Problem Solving/bon-appetit.py
  Problem Solving/commonChild.cpp
  Problem Solving/counting-valley.py
  Problem Solving/larry'sArray.cpp
  Ruby/apple_and_orange.rb
Labels: hacktoberfest-accepted

#300 Added solution to Small Triangles Large Triangles problem and updated readme file
  C/README.md
  C/SmallTrianglesLargeTriangles.c
Labels: hacktoberfest-accepted

#114 Branch1
  Java/README.md
  Java/java_substring_comparisons
  java_substring_comparisons2.java
Labels: incomplete, invalid

#305 Swift folder added + 3 HRank algorithm
  Swift/CaesarCipher.playground/Contents.swift
  Swift/CaesarCipher.playground/contents.xcplayground
  Swift/CaesarCipher.playground/playground.xcworkspace/contents.xcworkspacedata
  Swift/CaesarCipher.playground/playground.xcworkspace/xcuserdata/camiloibarrayepes.xcuserdatad/UserInterfaceState.xcuserstate
  Swift/appleAndOranges.playground/Contents.swift
  Swift/appleAndOranges.playground/contents.xcplayground
  Swift/appleAndOranges.playground/playground.xcworkspace/contents.xcworkspacedata
  Swift/appleAndOranges.playground/playground.xcworkspace/xcuserdata/camiloibarrayepes.xcuserdatad/UserInterfaceState.xcuserstate
Labels: incomplete

#139 added PrintPattern problem under C
  C/Print_Pattern.c
  C/README.md
Labels: hacktoberfest-accepted

#140 Updated Itertools file
  Python/ItertoolsCombinations.py
Labels: hacktoberfest-accepted

#131 Create TriangleQuest2.py - pattern printing
  Python/TriangleQuest2.py
Labels: hacktoberfest-accepted

#130 max_out_of_4 number code added in C
  C/max_out_of_4.c
Labels: hacktoberfest-accepted

#141 Loops.py
  Python/Loops.py
Labels: hacktoberfest-accepted

#198 o_First_non-repeating_integer.py
  Python/o_First_non-repeating_integer.py
Labels: incomplete

#110 created Binary Search.py
  Algorithms/A_Very_Big_Sum.py
Labels: incomplete

#182 java files added
  30 Days Of Code (Java)/Day-0-HelloWorld.java
  30 Days Of Code (Java)/Day-1-DataTypes.java
  30 Days Of Code (Java)/Readme.md
Labels: incomplete
